# -*- coding: utf-8 -*-
"""Construct NN from scratch

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uHapyhkix3WkdohgV1mFznASMU_IJiiI
"""

import numpy as np

class NeuralNetwork:
    def __init__(self, layer_sizes):
        """
        layer_sizes: list of integers [input_size, hidden1_size, ..., output_size]
        """
        self.layer_sizes = layer_sizes
        self.num_layers = len(layer_sizes)

        # Initialize parameters
        self.weights = []
        self.biases = []

        # He/Xavier initialization for better convergence
        for i in range(self.num_layers - 1):
            w = np.random.randn(layer_sizes[i], layer_sizes[i+1]) * np.sqrt(2.0 / layer_sizes[i])
            b = np.zeros((1, layer_sizes[i+1]))
            self.weights.append(w)
            self.biases.append(b)

class ActivationFunctions:
    @staticmethod
    def relu(x):
        """ReLU activation"""
        return np.maximum(0, x)

    @staticmethod
    def relu_derivative(x):
        """Derivative of ReLU"""
        return (x > 0).astype(float)

    @staticmethod
    def sigmoid(x):
        """Sigmoid activation"""
        return 1 / (1 + np.exp(-np.clip(x, -500, 500)))  # Clip for numerical stability

    @staticmethod
    def sigmoid_derivative(x):
        """Derivative of sigmoid"""
        sig = ActivationFunctions.sigmoid(x)
        return sig * (1 - sig)

    @staticmethod
    def tanh(x):
        """Tanh activation"""
        return np.tanh(x)

    @staticmethod
    def tanh_derivative(x):
        """Derivative of tanh"""
        return 1 - np.tanh(x)**2

    @staticmethod
    def softmax(x):
        """Softmax for output layer"""
        exp_x = np.exp(x - np.max(x, axis=1, keepdims=True))
        return exp_x / np.sum(exp_x, axis=1, keepdims=True)

class NeuralNetworkFromScratch:
    def __init__(self, layer_sizes, activation='relu', output_activation='softmax'):
        self.layer_sizes = layer_sizes
        self.activation = activation
        self.output_activation = output_activation

        # Initialize weights and biases
        self.weights = []
        self.biases = []

        for i in range(len(layer_sizes) - 1):
            # He initialization for ReLU, Xavier for others
            if activation == 'relu':
                w = np.random.randn(layer_sizes[i], layer_sizes[i+1]) * np.sqrt(2.0 / layer_sizes[i])
            else:
                w = np.random.randn(layer_sizes[i], layer_sizes[i+1]) * np.sqrt(1.0 / layer_sizes[i])
            b = np.zeros((1, layer_sizes[i+1]))
            self.weights.append(w)
            self.biases.append(b)

        # Store activations and linear outputs for backprop
        self.activations = []
        self.z_values = []

    def _activation_function(self, x, derivative=False):
        """Apply activation function or its derivative"""
        if derivative:
            if self.activation == 'relu':
                return ActivationFunctions.relu_derivative(x)
            elif self.activation == 'sigmoid':
                return ActivationFunctions.sigmoid_derivative(x)
            elif self.activation == 'tanh':
                return ActivationFunctions.tanh_derivative(x)
        else:
            if self.activation == 'relu':
                return ActivationFunctions.relu(x)
            elif self.activation == 'sigmoid':
                return ActivationFunctions.sigmoid(x)
            elif self.activation == 'tanh':
                return ActivationFunctions.tanh(x)

    def forward(self, X):
        """Forward propagation"""
        self.activations = [X]
        self.z_values = []

        # Hidden layers
        for i in range(len(self.weights) - 1):
            z = np.dot(self.activations[-1], self.weights[i]) + self.biases[i]
            self.z_values.append(z)
            a = self._activation_function(z)
            self.activations.append(a)

        # Output layer
        z_final = np.dot(self.activations[-1], self.weights[-1]) + self.biases[-1]
        self.z_values.append(z_final)

        if self.output_activation == 'softmax':
            a_final = ActivationFunctions.softmax(z_final)
        elif self.output_activation == 'sigmoid':
            a_final = ActivationFunctions.sigmoid(z_final)
        else:
            a_final = z_final

        self.activations.append(a_final)
        return a_final

    def backward(self, X, y, learning_rate):
        """Backward propagation"""
        m = X.shape[0]  # Number of samples

        # Initialize gradients
        dW = [np.zeros_like(w) for w in self.weights]
        db = [np.zeros_like(b) for b in self.biases]

        # Output layer error
        if self.output_activation == 'softmax':
            # For softmax with cross-entropy loss
            da = self.activations[-1] - y
        else:
            # For other activations with MSE loss
            da = self.activations[-1] - y

        # Backpropagate through output layer
        dz = da
        dW[-1] = np.dot(self.activations[-2].T, dz) / m
        db[-1] = np.sum(dz, axis=0, keepdims=True) / m

        # Backpropagate through hidden layers
        for i in range(len(self.weights) - 2, -1, -1):
            da = np.dot(dz, self.weights[i+1].T)
            dz = da * self._activation_function(self.z_values[i], derivative=True)
            dW[i] = np.dot(self.activations[i].T, dz) / m
            db[i] = np.sum(dz, axis=0, keepdims=True) / m

        # Update parameters
        for i in range(len(self.weights)):
            self.weights[i] -= learning_rate * dW[i]
            self.biases[i] -= learning_rate * db[i]

    def train(self, X, y, epochs, learning_rate, verbose=True):
        """Train the neural network"""
        losses = []

        for epoch in range(epochs):
            # Forward pass
            predictions = self.forward(X)

            # Compute loss
            if self.output_activation == 'softmax':
                loss = -np.mean(np.sum(y * np.log(predictions + 1e-8), axis=1))
            else:
                loss = np.mean((predictions - y)**2)

            losses.append(loss)

            # Backward pass
            self.backward(X, y, learning_rate)

            if verbose and epoch % (epochs // 10) == 0:
                print(f"Epoch {epoch}, Loss: {loss:.6f}")

        return losses

    def predict(self, X):
        """Make predictions"""
        predictions = self.forward(X)
        if self.output_activation == 'softmax':
            return np.argmax(predictions, axis=1)
        else:
            return predictions

# Example 1: Binary Classification
def create_sample_data():
    """Create simple XOR dataset"""
    X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
    y = np.array([[0], [1], [1], [0]])
    return X, y

# Create and train network
X, y = create_sample_data()
nn = NeuralNetworkFromScratch([2, 4, 1], activation='relu', output_activation='sigmoid')
losses = nn.train(X, y, epochs=1000, learning_rate=0.5)

# Make predictions
predictions = nn.predict(X)
print("Predictions:", predictions)

# Example 2: Multi-class Classification
def create_multi_class_data():
    """Create simple multi-class dataset"""
    X = np.random.randn(100, 2)
    y = np.zeros((100, 3))
    for i in range(100):
        if X[i, 0] + X[i, 1] > 0:
            y[i] = [1, 0, 0]
        elif X[i, 0] - X[i, 1] > 0:
            y[i] = [0, 1, 0]
        else:
            y[i] = [0, 0, 1]
    return X, y

# Create and train multi-class network
X_multi, y_multi = create_multi_class_data()
nn_multi = NeuralNetworkFromScratch([2, 8, 3], activation='relu', output_activation='softmax')
losses_multi = nn_multi.train(X_multi, y_multi, epochs=500, learning_rate=0.1)

# Add dropout for regularization
class DropoutLayer:
    def __init__(self, dropout_rate=0.5):
        self.dropout_rate = dropout_rate
        self.mask = None

    def forward(self, x, training=True):
        if training:
            self.mask = np.random.binomial(1, 1-self.dropout_rate, size=x.shape) / (1-self.dropout_rate)
            return x * self.mask
        return x

    def backward(self, grad_output):
        return grad_output * self.mask

# Add batch normalization
class BatchNorm:
    def __init__(self, num_features, epsilon=1e-8):
        self.gamma = np.ones((1, num_features))
        self.beta = np.zeros((1, num_features))
        self.epsilon = epsilon
        self.running_mean = np.zeros((1, num_features))
        self.running_var = np.ones((1, num_features))

    def forward(self, x, training=True):
        if training:
            mean = np.mean(x, axis=0, keepdims=True)
            var = np.var(x, axis=0, keepdims=True)
            self.running_mean = 0.9 * self.running_mean + 0.1 * mean
            self.running_var = 0.9 * self.running_var + 0.1 * var
        else:
            mean = self.running_mean
            var = self.running_var

        x_norm = (x - mean) / np.sqrt(var + self.epsilon)
        return self.gamma * x_norm + self.beta
        print(self.gamma)
        print(mean)
        print(var)
        print(x_norm)
        print(self.gamma)
        print(self.beta)

